Merge feature/working_branch into development.
Joseph-Burke/Micro-Reddit pull request #1
Opened 2020-09-02 14:27 UTC by Joseph-Burke

The authors request to merge **feature/working_branch** into **development** following the completion of the entire Odin project assignment.

- Created models for User, Post and Comment.
- Ensured the correct relationships between models using _has_many_ and _belongs_to_
- Created migration files for each model.
- Tested relationships in the console as per instructions.

2020-09-02 18:12 UTC, wathigo requested changes
### Changes Required.
Great work guys :clap:
I have successfully created a user, post, and comments successfully.
The association between entities has been implemented in the right way.
We have one hard requirement we need to meet before marking this as done.

**REQUIRED**
Let's add body and title fields and validations to the post entity as shown in the comments :point_down: .

**Happy Hacking :computer: 
Simon Wathigo.**

2020-09-02 18:12 UTC, wathigo commented on app/models/post.rb
> +end
**REQUIRED**
* validations are present (body and title in automated tests but can be anything else) ([screenshot](validations are present (body and title in automated tests but can be anything else) (screenshot from Odin Project)) from Odin Project)

2020-09-03 08:05 UTC, Joseph-Burke commented on app/models/post.rb
> +end
A new migration has been exchanged with the **Post** table to remove the **link_url** column and add **title** and **body** columns. These two columns now also have presence validations, as requested.
<img width="1367" alt="Screenshot 2020-09-03 at 09 02 24" src="https://user-images.githubusercontent.com/56026099/92088217-7de8c080-edc4-11ea-96c3-a26ff95b1996.png">

2020-09-03 08:39 UTC, rOluochKe requested changes
Hello @Joseph-Burke and @Maryjanee 
### Good job you have done :clap: However, you need to add linter in the project and solve the errors that will be displayed [refer this article](https://github.com/microverseinc/linters-config/tree/master/ruby) - At Microverse we use github actions
### Make the changes and submit for another code review. Good luck.
- Happy hacking!

By Raymond
Slack @iamraymond

2020-09-03 09:34 UTC, Joseph-Burke commented
.rubocop.yml and .github/workflows/linters.yml have now been added to the project, and the project is now passing all tests in GitHub Actions.

2020-09-03 09:41 UTC, rOluochKe approved these changes
Hello @Joseph-Burke and @Maryjanee 
### Well done :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

2020-09-03 09:45 UTC, merged